Algoritmo "semnome"

// 3. Faça um algoritmo que:
// a) Leia um número inteiro;
// b) Leia um segundo número inteiro;
// c) Efetue a adição dos dois valores;
// d) Apresente o valor calculado.
Var
   nome1, nome2, nome3: caracter

Inicio
   escreval("digite seu 1 nome: ")
   leia(nome1)
   escreval("digite seu 2 nome: ")
   leia(nome2)
   nome3 <- (nome1 + nome2)
   escreval("seu nome completo é: ", nome3)
Fimalgoritmo